# Site settings
title: MAGICAL PATCHES
email: ruif_ken@163.com
url: http://magicalpatches.com
description: "Magic patch is dedicated to providing customers with better, professional patches!"


# Team names, titles and social links
people:
- name: Machine production
  pic: xiuhuaji
  position: Efficient and mass production

- name: Laser cut
  pic: laser_cut
  position: Uniform cutting, uniform quality
  
- name: Hand crafted
  pic: hand_crafted
  position: Complex and diverse processes， more artistic

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Magical_Patches
  - title: facebook
    url:
  - title: pinterest
    url: http://pinterest.com
  - title: instagram 
    url: https://www.instagram.com/magicalpatches/
  - title: google-plus
    url: https://plus.google.com/s/Magical_Patches/top

# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty
