# Site settings
title: MAGICAL PATCHES
email: your-email@domain.com
url: http://withewind.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Machine production
  pic: xiuhuaji
  position: Machine production

- name: Laser cut
  pic: laser_cut
  position: Laser cut
  
- name: Diana Petersen
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Magical_Patches
  - title: facebook
    url:
  - title: pinterest
    url: http://pinterest.com
  - title: instagram 
    url: https://www.instagram.com/magicalpatches/
  - title: google-plus
    url: http://plus.google.com

# Postal address (add as many lines as necessary)

# Build settings
markdown: kramdown
permalink: pretty
